import React from 'react';
import { Sparkles, Info } from 'lucide-react';

interface AiBadgeProps {
  className?: string;
}

export function AiBadge({ className }: AiBadgeProps) {
  return (
    <span
      className={`badge badge-ai ${className || ''}`}
      data-testid="ai-summary-badge"
      title="This summary was automatically generated by an AI pipeline from verified source posts"
    >
      <Sparkles size={12} className="ai-icon" />
      <span>AI-Generated Summary</span>
    </span>
  );
}

interface AiSummaryBoxProps {
  summary: string;
  isAiGenerated: boolean;
}

export function AiSummaryBox({ summary, isAiGenerated }: AiSummaryBoxProps) {
  if (!summary) return null;

  return (
    <section className="ai-summary-box" aria-labelledby="ai-summary-heading">
      <div className="ai-summary-header">
        <div className="ai-summary-badge-group">
          <h2 id="ai-summary-heading" style={{ fontSize: '1rem', fontWeight: 600 }}>
            Executive Summary
          </h2>
          {isAiGenerated && <AiBadge />}
        </div>
      </div>
      <p className="ai-summary-text">{summary}</p>
      {isAiGenerated && (
        <div className="ai-summary-disclaimer">
          <Info size={13} />
          <span>
            Synthesized automatically from channel reports. Verify critical details with
            the primary sources below.
          </span>
        </div>
      )}
    </section>
  );
}
